nixos-org/planet-feeds.nix
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-org-configurations/10)
=> planet.nixos.org: updated mine feed url

nixos-org/hydra-mirror.nix
=> Add 17.03 channel

nixos-org/webserver.nix
Extracted from https://github.com/NixOS/nixos-org-configurations/pull/30 , this one should be pretty easy to merge.
=> cleanup: remove long-dead repoman and svn services

nixos-org/webserver.nix
I think the commits make it easy to follow, untested of course :/
=> HTTPS on planet.nixos.org

nixos-org/hydra-mirror.nix
See https://github.com/NixOS/nixpkgs/issues/25479
cc @edolstra
=> Add stable darwin release following NixOS 17.09 branch

nixos-org/planet-feeds.nix
=> Add my blog

delft/hydra.nix
Not sure how to actually tell Hydra to use it, though.
=> add packet-epyc-1

nixos-org/hydra-mirror.nix
If there is a need, or want, to remove previous channels, it can be handled in another PR.
=> channels: Add 18.09

README.md
[rendered](https://github.com/zimbatm/nixos-org-configurations/blob/dcf91b33639a4ba8b70cc0a2674b82090ced27bb/README.md)
=> README: add file with basic structure

bastion/network.nix, terraform/README.md, terraform/providers.tf, terraform/shell.nix
Prepare to manage Fastly with terraform
=> Tf fastly prepare

nixos-org/planet-feeds.nix
Add the NixOS atom feed for Craige McWhirter
=> planet-nixos: add Craige McWhirter

modules/hydra-mirror.nix
This creates the 19.09 channel for the release.
@edolstra @rbvermaa @lheckemann
=> 19.09 channel addition

delft/prometheus/hydra-queue-runner-reexporter.py
This should unbreak https://status.nixos.org/grafana which currently
doesn't show any details about the hydra queues and runners.
This is probably required due to https://github.com/NixOS/hydra/pull/668.
=> hydra-queue-runner-reexporter: Treat notification metrics as optional

delft/eris.nix
Due to https://github.com/NixOS/nixos-homepage/pull/330
=> Remove checks for update script for nixos.org website

delft/eris/channel-exporter.py
Currently the exporter gets stuck sometimes, perhaps there are some
concurrency issues with unregistering/registering dynamically.
/cc @grahamc
=> remove custom registry from channel exporter

channels.nix
Ref to past PR https://github.com/NixOS/nixos-org-configurations/pull/100
=> 20.09 channels

channels.nix
related: https://github.com/NixOS/nixpkgs/issues/101975
=> 20.03 is EOL

macs/notes.md
An additional step I found I needed to take on catalina and a formatting fix.
=> small fixes to mac setup "notes"

channels.nix
Add related 21.05 channels. Jobsets have been running for ~week now
=> Add 21.05 channels

terraform/nixpkgs-tarballs.tf
=> terraform/nixpkgs-tarballs: add lovesegfault to upload list

terraform/dns.tf
Two follow-up commits after #176 
Fixes #177
=> Tf netlify status

channels.nix
=> Include 21.11 channels

delft/eris/channel-exporter.py
Oops. I added new things to the CHANNEL_REVISION object, but didn't
update that down here.
=> channel-exporter: provide necessary information to remove from dict

delft/eris.nix
Quite recently the `/scratch` partition on bastion ran out of free disk
space.
This is an update to the alerting rule to generalize and extend the
existing disk fullness alerts.
In addition to monitoring `/scratch` we are now sharing the filesystem
selector between these rules and in addition monitor relative fullness
on them.
=> delft/eris: update disk monitoring alerts

terraform/cache.tf
This should fix the issue we're seeing in #207
=> terraform: enable segment caching for NAR files

bastion/flake.lock
Picks up https://github.com/NixOS/nixos-channel-scripts/pull/63.
=> bastion: bump nixos-channel-scripts

channels.nix
=> channels: Mark 22.05 unmaintained

delft/eris.nix
The metrics we've been collecting at github:NixOS/nixos-metrics are currently viewable at https://nixos.github.io/nixos-metrics/. It would be nice to get them into the community Grafana, so people will know where to find them and so they can be accessed using all of Grafana's fancy features (data analysis, comparison to other metrics, etc).
We are aiming to use VictoriaMetrics rather than Prometheus because
1. It allows us to add more metrics downstream that will automatically get picked up without making a PR here every time
2. It allows back-filling the data we've already collected.
I'm not sure if there's an easy way to allow external yet secure access directly to the VictoriaMetrics instance. So instead I've opted for the server to *pull* data and push it to VictoriaMetrics …
=> add NixOS/nixos-metrics metrics via VictoriaMetrics

delft/eris/alertmanager-matrix-forwarder.nix, delft/flake.nix
This will probably fix matrix alerts.
=> eris: fix go-neb secret ownership

channels.nix
=> channels: Add NixOS 23.05 as beta

channels.nix
Process docs: https://nixos.github.io/release-wiki/EOL-Cleanup.html
=> channels: 22.11 is EOL

.gitignore, non-critical-infra/.envrc, non-critical-infra/flake.lock, non-critical-infra/flake.nix, non-critical-infra/hosts/hetzner-01/default.nix, non-critical-infra/hosts/hetzner-01/disko.nix, non-critical-infra/hosts/hetzner-01/hardware.nix
Closes https://github.com/NixOS/nixos-org-configurations/issues/260
I have bootstrapped the machine for the non-critical infra team. 
Added keys for @zimbatm, @mweinelt and myself so far. This PR is for information (because the machine has de facto the configuration described here) and I will merge it after 24h.
=> non-critical-infra: hetzner-01 bootstraping

non-critical-infra/ReadMe.md
WIP: Would be good to start having processes to manager accesses to machines, secrets etc.
=> non-critical-infra: add readme

terraform/dns.tf
In preparation for an upcoming PR deploying vaultwarden
=> add dns record for vault.nixos.org

non-critical-infra/hosts/umbriel.nixos.org/default.nix, non-critical-infra/hosts/umbriel.nixos.org/disko.nix, non-critical-infra/hosts/umbriel.nixos.org/hardware.nix, terraform/dns.tf
This is an ARM64 VM at Hetzner Cloud, that we plan to use for the Matrix moderation bot Mjölnir.
=> umbriel: init

non-critical-infra/flake.lock, non-critical-infra/flake.nix
- infinite recursion in first-time-contribution-tagger (@Janik-Haag was notified)
=> non-critical-infra: update to nixos-23.11

channels.nix
EOL was on 2023-12-31
Happy new year!
=> channels: 23.05 is unmaintained

ssh-keys.nix
As discussed with @zimbatm. Looking forward to helping take care of the health of NixOS's build infra, fixing technical debt, reacting to new and exciting infra changes coming in 2024, etc. :-)
=> ssh-keys: infra-core += delroth

terraform/dns.tf
Had to pull the server down, since I don't have time to maintain it anymore.
=> Remove live.nixos.org from DNS

README.md
=> README: document regular catch up

terraform/dns.tf
In prevision for the deployment of the wiki.
=> dns: add records for wiki.nixos.org

docs/meeting-notes/2024-01-11.md, docs/meeting-notes/2024-01-25.md, docs/meeting-notes/2024-02-08.md
As discussed on 2024-02-08. Please have a look to check whether the contents are what you'd expect them to be.
=> docs: add infra meeting notes

delft/eris.nix
=> Scrape domain expiration dates in Prometheus

delft/flake.lock, delft/flake.nix, delft/pluto/boot.nix, delft/pluto/default.nix, delft/pluto/disko.nix, delft/pluto/network.nix, modules/wireguard-hosts.toml, terraform/dns.tf
The machine is live. DNS is updated.
=> pluto: init

ssh-keys.nix
In a context where we are reminded of how critical is it to apply the least privilege, it's always good to maintain our most critical infrastructures.
I tried to reach out to @grahamc and @AmineChikhaoui to no avail.
We discussed this with @edolstra during last infrastructure meeting, and they consented to the effects of this PR.
PTAL @zimbatm @mweinelt.
=> ssh-keys: update to set of people actively working on the infra-core

ssh-keys.nix
=> ssh-keys: infra-core += delroth again

ssh-keys.nix
* Remove unused keys
* Add missing members
=> ssh-keys: cleanup

delft/haumea/zrepl.nix, modules/wireguard-hosts.toml
Thanks for helping with the infra!
=> remove delroth's config

non-critical-infra/modules/postfix.nix, non-critical-infra/modules/vaultwarden.nix, non-critical-infra/secrets/opendkim-private-key.caliban, non-critical-infra/secrets/vaultwarden-env.caliban, terraform/dns.tf
Tried a test email with the admin interface
Fixes #430
=> vaultwarden: use local mailer

non-critical-infra/hosts/caliban.nixos.org/default.nix, non-critical-infra/modules/owncast.nix, terraform/dns.tf
Deploys owncast under live.nixos.org.
=> non-critical-infra/owncast: init

non-critical-infra/.sops.yaml, ssh-keys.nix
My motivation to contribute to the NixOS infra has taken a big hit since the governance issues in the NixOS community, unfortunately.
=> non-critical-infra: remove julienmalka's credentials

macs/nix-darwin.nix
Somehow the formatting of this file got messed up. It's causing CI to fail.
=> Run `nix fmt`

build/scripts/nix-mac-installer.sh, build/scripts/nix-mac-nuke.sh, formatter/flake-module.nix, metrics/fastly/cron.sh, metrics/fastly/ingest-raw-logs.sh, metrics/fastly/run-queries.sh, modules/prometheus/system-version-exporter.sh
I saw the TODO in `formatter/flake-module.nix` and thought I'd deal with it.
=> Enable shellcheck, address errors

build/datadog/hydra.py, build/pluto/prometheus/exporters/channel-exporter.py, build/pluto/prometheus/exporters/hydra-queue-runner-reexporter.py, formatter/flake-module.nix, hydra-packet-importer/import.py
`ruff` complained about a few issues in our codebase. I've addressed them.
=> Add `ruff-check`

flake.lock, macs/nix-darwin.nix, non-critical-infra/modules/mailserver/mailing-lists.nix
This fixes https://github.com/NixOS/infra/issues/505
=> Reload `postfix-setup` when mailing list membership changes

build/common.nix, modules/rasdaemon.nix, non-critical-infra/hosts/caliban.nixos.org/default.nix
Part of #518 
```
[root@haumea:~]# ras-mc-ctl --errors
No Memory errors.
No PCIe AER errors.
No ARM processor errors.
No Extlog errors.
No devlink errors.
No disk errors.
No Memory failure errors.
MCE events:
1 2024-12-19 03:52:38 +0000 error: Corrected error, no action required., CPU 2, bank Unified Memory Controller (bank=17), mcg mcgstatus=0, mci CECC, memory_channel=0,csrow=1, mcgcap=0x0000011c, status=0x9c2040000000011b, addr=0x319deb440, misc=0xd01b0fff01000000, walltime=0x67639886, cpuid=0x00870f10, bank=0x00000011
2 2024-12-20 09:33:01 +0000 error: Corrected error, no action required., CPU 2, bank Unified Memory Controller (bank=17), mcg mcgstatus=0, mci CECC, memory_channel=0,csrow=1, mcgcap=0x0000011c, status=0x9c2040000000011b, addr=0x319deb440, misc=0xd01b0fff01000000, …
```
=> Enable rasdaemon on all bare metal Linux hosts

build/haumea/postgresql.nix, build/hydra-proxy.nix, build/nginx-error-pages/502.html, build/pluto/prometheus/exporters/zfs.nix
A mixed bag of things that came up yesterday and today.
=> hydra: abuse handling, branded 502 error; prometheus: alert on full zfs pool

build/flake.lock, build/pluto/prometheus/exporters/blackbox.nix
To avoid potential alerting noise: I'll wait until this is deployed and succeeding before declaring an additional alert.
refs: https://github.com/NixOS/infra/issues/485
refs: https://github.com/Thaigersprint/thaigersprint-2025/issues/1
=> Add a blackbox monitor of our mailserver

non-critical-infra/modules/mailserver/mailing-lists.nix
As per https://github.com/NixOS/org/pull/95#discussion_r2028754727
NOTE: This only affects umbriel ([which will very soon be the new nixos.org mailserver](https://github.com/NixOS/infra/issues/587)). I have not updated ImprovMX because I do not have access.
NOTE 2: Do not merge/deploy this until after https://github.com/NixOS/org/pull/95#discussion_r2028756165 is deployed.
=> Add sponsor@

build/pluto/prometheus/exporters/blackbox.nix, dns/nixos.org.js, non-critical-infra/modules/mailserver/README.md
This is step 2 of https://github.com/NixOS/infra/issues/587
=> Switch our MX record(s) from ImprovMX to `umbriel.nixos.org`

non-critical-infra/modules/mailserver/mailing-lists.nix, non-critical-infra/secrets/Mic92-wiki-email-address.umbriel, non-critical-infra/secrets/hehongbo-xsa-email-address.umbriel, non-critical-infra/secrets/lach-xsa-email-address.umbriel, non-critical-infra/secrets/lassulus-wiki-email-address.umbriel, non-critical-infra/secrets/sigmasquadron-xsa-email-address.umbriel
Apparently only the first page of aliases were migrated.
Additionally, claim a bunch of localparts for the infra team.
=> Add missing mail aliases

non-critical-infra/modules/mailserver/postsrsd.nix
Also ensure service restarts on secret rotation.
=> fix: use correct user/group for secret

build/pluto/prometheus/exporters/blackbox.nix, dns/nixos.org.js, non-critical-infra/modules/mailserver/README.md
Now that https://github.com/NixOS/infra/pull/622 has landed, I believe we're ready to try this again.
This reverts commit 5a6958d0002501486eb87714084c469369a78ac6.
CC @infinisil to confirm that things are working after this lands.
=> Roll out umbriel as our mailserver (again)

.github/workflows/dns-preview.yml
Closes: #630
Via https://github.com/orgs/community/discussions/25217
=> Run dnscontrol previews only for local branches

non-critical-infra/modules/mailserver/mailing-lists.nix, non-critical-infra/secrets/escherlies-email-address.umbriel, non-critical-infra/secrets/nlewo-email-address.umbriel
https://github.com/NixOS/org/pull/98
@nlewo's email is from the Nixpkgs maintainers list (let me know if a different one should be used)
@escherlies' is from PMs
=> More NixCon organiser emails

dns/dnsconfig.js, dns/nix.dev.js, dns/ofborg.org.js
CI is expected to fail as long as the nameserver migration is incomplete.
=> dns: manage ofborg.org, nix.dev

.github/workflows/ci.yml
this job is building .#checks
This also needs to be updated in our branch protection.
=> rename nix-build to checks

non-critical-infra/modules/mailserver/mailing-lists.nix, non-critical-infra/secrets/fmehta-email-address.umbriel
Is an organiser: https://2025.nixcon.org/organizers
=> Add @fmehta's email to the nixcon organisers

build/hydra-proxy.nix, build/nginx-error-pages/403.html
and give hints on how to resolve the block.
=> hydra-proxy: serve branded 403 page

build/nginx-error-pages/403.html, build/nginx-error-pages/502.html, terraform/cache-staging/index.html, terraform/cache/index.html, terraform/nixpkgs-tarballs/index.html
This completes https://github.com/NixOS/infra/issues/709.
=> Fix broken logo

non-critical-infra/modules/mailserver/mailing-lists.nix, non-critical-infra/secrets/ral-email-address.umbriel
https://2025.nixcon.org/organizers
https://github.com/nixcon/2025.nixcon.org/pull/36
=> Update NixCon mailing list to match new organiser list

flake.lock, non-critical-infra/modules/mailserver/freescout.nix
https://cyberchaos.dev/e1mo/freescout-nix-flake/-/merge_requests/1 has landed upstream. We can remove this workaround =)
=> Upgrade freescout, remove `package` workaround

non-critical-infra/modules/mailserver/mailing-lists.nix, non-critical-infra/secrets/finance-email-login.umbriel
Allows onboarding onto freescout, just like foundation@
Will set it up to be accessible by all foundation members and Kate
=> Store email and allow login for finance@nixos.org

README.md, terraform/cache-staging.tf, terraform/cache-staging/index.html, terraform/cache.tf, terraform/cache/index.html, terraform/nixpkgs-tarballs/index.html
As (awkwardly) discovered in https://github.com/NixOS/infra/pull/689#issuecomment-3006374949
=> treewide: update outdated URLs

non-critical-infra/modules/mailserver/mailing-lists.nix, non-critical-infra/secrets/hardware-email-login.umbriel
@Mic92 requested the hardware team to use freescout too.
I'll send the email password to Mic92 to put into the vault, though not strictly necessary as it's set-and-forget in freescout.
Same as #748 and #746
=> Store hardware team emails to be able to set up freescout

.github/workflows/ci.yml, non-critical-infra/hosts/staging-hydra/bootstrap-staging-hydra.sh, non-critical-infra/hosts/staging-hydra/hardware.nix
Only half the money per month.
=> Switch staging hydra to aarch64-linux

non-critical-infra/modules/mailserver/mailing-lists.nix, non-critical-infra/secrets/steering-email-login.umbriel
In preparation to onboarding onto freescout.
A majority of @NixOS/steering have privately agreed with doing this :)
=> Set up password and store email for SC

dns/nixcon.org.js
We'll be hosting a small game for the NixCon crowd.
=> dns: update bee.nixcon.org cname

non-critical-infra/hosts/caliban/nixpkgs-swh.nix
Follow up of https://github.com/NixOS/infra/pull/830 to address @mweinelt comments.
=> caliban: fix the nixpkgs-swh expression

non-critical-infra/modules/mailserver/mailing-lists.nix, non-critical-infra/secrets/nixpkgs-core-email-login.umbriel
For https://discourse.nixos.org/t/establishing-the-nixpkgs-core-team/69743
Ping @NixOs/nixpkgs-core
=> Add nixpkgs-core email
