NixOS/infra

nixos-org/planet-feeds.nix
We're going to cover NixOS stuff in our company blog in the future.
=> Flying Circus NixOS-related blog posts

nixos-org/hydra-mirror.nix
Note that `nixos-version` shows `_beta` instead of `_pre` for 16.09.
In last release we also put beta in the channel name, I'd strongly prefer not to do that again.
Switching channel twice per release is painful state handling and especially bad UX since beta channel literally disappear/stagnates once final 16.09 is released.
cc @edolstra
=> Add 16.09 channel

nixos-org/tarball-mirror.nix, nixos-org/webserver.nix
As soon as https://hydra.nixos.org/build/51054560 passes we have a stable 17.03 channel bump.
cc @edolstra
=> NixOS 17.03

nixos-org/webserver.nix
- repoman 404's so remove the svn redirect
- remove the long-commented svn subservice
- stop serving the wiki, remove related redirects, and remove related pgsql config
I don't mean this to be a forever thing, I think having the wiki in a middle phase between "is old and out of date and not fixable" and "we're wanting to fix it soon(?)" is the worst option. Nobody sees the "being shut down" message.
cc @copumpkin
=> Remove Dead and Deprecated Web Services

delft/delft-webserver.nix, delft/hydra-proxy.nix, nixos-org/webserver.nix
HSTS tells the browser that you should always use HTTPS when
talking to the domain, for the next max-age. This means it will
(in-browser) redirect from http to https, without hitting a
the webserver.
- max-age is set to 1 day in case of problems, in the future I'd
like to extend this.
- we can't enable includeSubdomains because the following
domains don't use TLS:
- www.nixos.org (redirects to nixos.org)
- releases.nixos.org (deprecated? how much traffic does this get?)
- planet.nixos.org
If we can fix these, we can add includeSubdomains too.
Obviously I haven't tested this, as I don't have a local copy of
nixos.org running :)
=> Enable HSTS and fixup http:// links

delft/hydra-proxy.nix, nixos-org/webserver.nix
6mo is long enough we are a step closer to being able to "preload" hsts support. After this, we'd need to ensure all subdomains supported HSTS. Do you have a list?
- releases.nixos.org
- planet.nixos.org
- hydra.nixos.org
- test.nixos.org
- test2.nixos.org
- ipv6.nixos.org
anything I missed?
=> hsts: increase age to 6 months

nixos-org/webserver.nix
Currently https://www.nixos.org/ is an SSL certificate CN mismatch error page. :(
=> www.nixos.org: serve an SSL certificate

nixos-org/hydra-mirror.nix
I assume we can call the channels with the usual names _already_, and they'll be simply considered beta until officially announced to be released in a few weeks.  They're forked -unstable ATM, so nothing dangerous, really.
=> channels: add 18.03 versions

terraform/releases.tf
I wanted to build a JavaScript-only version of howoldis.herokuapp.com but this requires some CORS enabled on the releases bucket.
Run this command to import the existing bucket into the state:
terraform import aws_s3_bucket.releases nix-releases
=> terraform releases bucket

terraform/cache.tf, terraform/nixpkgs-tarballs.tf, terraform/releases.tf
Formatted with jq
nix-releases inherits the policy from nix-cache
should fix #70
=> terraform: update the bucket policies

terraform/route53.tf
Right now the DNS is hosted on the udag.org servers and not directly
changeable with code.
=> terraform: describe the nixos.org records in route53

lib/service-order.nix, modules/hydra-mirror.nix
Create a sequential ordering with systemd After-relationships between
each channel's update job. Then, remove individual timers and create
one timer for all the jobs.
Fixes #79
=> channel updates: make sequential

delft/chef.nix, delft/packet-importer.nix, hydra-packet-importer/config-example.json, hydra-packet-importer/default.nix, hydra-packet-importer/import.py, hydra-packet-importer/shell.nix
Packet lets us get cheap and powerful builders for our Hydra over Spot, but they change regularly. For that reason we don't want to manually update the configuration settings. Here is a simple Python program and systemd timer to import manage them automatically.
I've already deployed this, but would like some eyes on the branch anyway.
=> Automatically import Packet.net spot instances to Hydra

nixos-org/webserver.nix
Redirect the old page name to the new one.
Apply once https://github.com/NixOS/nixos-homepage/pull/318 has been
merged.
=> nixos-org: add redirect to learn page

delft/eris/status-page/status.js
Due to the fact that loading state text is inserted on window onload,
this insertion can potentially happen **after** all other async
actions are already finished and thus replace the actual data.
This fix makes sure that requests are triggered after onload is done.
cc @grahamc
This is what happens when the async actions are resolved with timing that leads to this issue:
1. make sure that **client side cache is disabled* in browser
- common way is to set "disable caching while developer console is open" and open the console
1. refresh page several times until you hit critical timing in which issue occures.
=> status-page: fix race condition in initialization.

delft/eris/status-page/index.html, delft/eris/status-page/status.css, delft/eris/status-page/status.js
=> status-page: add alerts for github issues

delft/eris.nix
Use the failed status over the last 5m instead of it's current value to
avoid triggering multiple alerts when the status flips briefly.
=> alertmanager: reduce alerts for flipping systemd states

delft/eris.nix
As requested, less spam on #nixos-dev. It would be easy to redirect these alerts to e.g. #nixos-infra, but I'll leave that decision to someone else, since I don't know who should respond to ChannelUpdateStuck in what manner and timeframe.
=> delft/eris: drop alerts with severity!='page', ignore stuck channels

terraform/releases.tf
I would need this to help migrate current artifacts in
nixos.org/releases to releases.nixos.org (nix-releases s3 bucket).
=> Requesting access to nix-releases S3 bucket

delft/eris/channel-exporter.py
This ensures the revision metric doesn't disappear while it's being
updated.
=> fix race condition in channel exporter

delft/eris/channel-exporter.py
According to the requests documentation there's no default timeout
whatsoever, which means the update loop can get stuck.
> If no timeout is specified explicitly, requests do not time out.
/cc @grahamc
=> add timeout to channel exporter requests

delft/eris/status-page/status.js
This removes the colour indicator from `Last updated` labels.
For outdated channels this label is now always grey.
cc @grahamc This is the change we've talked about in DMs on Twitter few days ago.
=> Avoid colour indications on outdated channels

delft/prometheus/hydra-queue-runner-reexporter.py
The upstream property memoryTokensInUse was removed by cbcf6359 [1] in
NixOS/Hydra#795 [2].
[1]: https://github.com/NixOS/hydra/pull/795/commits/cbcf6359b4b8525ab6252de2c3cc389397183159
[2]: https://github.com/NixOS/hydra/pull/795
=> hydra-queue-runner-reexporter: remove memory_tokens_in_use

delft/prometheus/packet-sd.nix
The previous version stopped working on 20.09 and this should unblock the deployment until https://github.com/NixOS/nixpkgs/pull/104500 / https://github.com/NixOS/nixpkgs/pull/104501 arrive in the stable channel of this box.
=> delft/prometheus/packet-sd: update to newer buildGoModule

delft/eris.nix
In NixOS 20.09, the listenAddress directive was changed to be purely
for the address and not for the address:port combination as previously.
This results in nginx now talking to *itself* using plaintext HTTP on
0.0.0.0. With forceSSL, this means nginx issues a redirect for the
hostname -> the client gets a redirect to
https://0.0.0.0/prometheus/....
Fixes #133
=> delft/eris: include Prometheus port in nginx proxy_pass directive

delft/eris.nix
This is step 2 from the https://github.com/NixOS/nixos-org-configurations/pull/137
=> Serve grafana and prometheus under monitoring.nixos.org

channels.nix
This adds a channel for NixOS 20.09 on AArcch64 based on the hydra
jobset that we already have.
The topic of an aarch64 specific channel has come up regular and as
these devices are gaining in popularity will only be discussed more
often.
This had been discussed on the nixpkgs issue tracker: https://github.com/NixOS/nixpkgs/issues/83049
=> Add AARCH64 channels for NixOS 20.09

terraform/cache.tf, terraform/channels.tf, terraform/nixpkgs-tarballs.tf, terraform/releases.tf
Cleanup after switching all the buckets to Fastly.
Waiting a few days in case we need to roll back.
=> tf: remove old CloudFront distributions

delft/eris.nix
This should consider *all* builds stuck over two days, not just those stuck between two days and three days.
=> eris: fix BuildsStuckOverTwoDays alert

terraform/dns.tf, terraform/flake.lock, terraform/flake.nix, terraform/netlify_sites.tf, terraform/providers.tf, terraform/terraform.tf
The goal of this PR is to import all of the Netlify resources into Terraform so their configuration is exposed to the community as a whole.
The Terraform provider DNS records are unfortunately not importable so I will have to delete them in the web UI, and hope that I didn't do copy-and-paste mistakes.
Backup of the DNS records in case I did some mistakes:
[dns-records-backup.json.gz](https://github.com/NixOS/nixos-org-configurations/files/7277785/dns-records-backup.json.gz)
TODO:
Records removed:
* All the old ACM validation records.
* `*.conf.nixos.org` and `*.weekly.nixos.org` as they don't seem necessary.
/cc @NixOS/nixos-homepage . going forwards, please don't edit things manually in Netlify. I'm going to rotate the shared password to avoid that.
Fixes #163
=> terraform: map netlify resources 

channels.nix, delft/eris.nix, delft/eris/channel-exporter.py
This can then be exported by prometheus in order to find the most recent
stable channel, as well as filter out variants such as small, aarch64,
and darwin channels.
---
Example query returning the latest stable NixOS version:
channel_revision{current="1",stable="1",variant=""}
The variant is empty when there is no set variant because `nixos-21.05`
is not a variant but the "base", while `nixos-21.05-small` is a "small"
variant of `nixos-21.05`.
=> Add `variant`, `status` fields to channels.nix, export them in channel-exporter

macs/guest-catalina/darwin-configuration.nix
Otherwise, if an admin ever needs to SSH in and run Nix commands, they
won't be able to and will get "command not found" errors without
crafting a NIX_PATH and running the binary from the system profile.
---
cc @grahamc
=> macs/guest-catalina: configure zsh

delft/eris.nix, delft/network.nix, delft/prometheus/fastly.nix, delft/prometheus/packet-sd.nix, delft/prometheus/postgres-exporter.nix
Reverts NixOS/nixos-org-configurations#195
```
error: attribute 'fastly-exporter' missing
at /nix/store/33zzxrj3kzlyv22qm3p7a703dp69cshd-source/nixos/modules/services/monitoring/prometheus/exporters/fastly.nix:35:9:
34|       "export FASTLY_API_TOKEN=$(cat ${toString cfg.tokenPath})"}
35|       ${pkgs.fastly-exporter}/bin/fastly-exporter \
|         ^
36|         -endpoint http://${cfg.listenAddress}:${cfg.port}/metrics
```
which I fixed with:
```
--- a/delft/network.nix
+++ b/delft/network.nix
@@ -49,6 +49,9 @@ in {
or (throw "Cannot deploy from an unclean source tree!");
nixpkgs.overlays = [
flakes.nix.overlay
+          (final: prev: {
+            fastly-exporter = final.prometheus-fastly-exporter;
+          })
];
```
which then revealed:
```
error: cannot coerce an integer to a …
```
=> Revert "Reuse prometheus-exporters from nixpkgs"

terraform/cache.tf
Because 404s are synthesized, these are cached somewhere after the cached-response headers are set, overriding the CORS header set on all responses. This means that, while any 200 can be read by a CORS-abiding HTTP client, 404s get `NetworkError`s.
I'm a little uncertain if this will entirely fix it, since it depends on the order that Fastly generates their VCL components in. (I believe the way synthetic responses are generated are by restarting, so that might cause the headers to not be stored, making this a simple fix.) I could not find a way to generate fastly's VCL, though, so no guarantees on correctness.
=> terraform/cache.tf: add CORS to response instead of cache

channels.nix
The promise was until the end of 2021, and there's almost
no backporting to 21.05 anymore.
=> channels: 21.05 is unmaintained

delft/eris.nix
We now round values to the nearest int, so we don't have an
unnecessarily high decimal precision.
Also we remove duplicate rule matches by reducing the number of labels
we look at.
=> delft/eris: update disk alerts

delft/eris.nix
> error: attribute 'annotations.summary' already defined at /nix/store/2378yi8aii8105vw132inlw5h03fvs70-source/delft/eris.nix:141:15
Fixing a copy/paste oopsie..
=> delft/eris: fix duplicate annotation in missing builder alert

delft/eris.nix
This cuts down alerts to scenarios that aren't caused by scheduling
alone. A builder type should see some usage in a two day window.
=> delft/eris: Increase lookback window in BuilderTypeMissing

delft/hydra.nix
A potential solution for https://github.com/NixOS/nixpkgs/issues/159612
Currently the Hydra nixos-unstable channel is clogged due to the Gnome ISO being just a tad bit bigger than 2GB. This results in the ISO build itself succeeding, but hydra marking the build as failing because of a failing validation check for the size. This has been the case for 6 days now. I'm suggesting this PR as a short-term solution. There are some critical CVE's that were fixed, but are not coming through right now (https://github.com/NixOS/nixpkgs/pull/160354).
The validation check for the output size seems to be here: https://github.com/NixOS/hydra/blob/f6e86efc9fc4f132cc183bc1c139fbaeeaa19238/src/hydra-queue-runner/build-remote.cc#L472-L475
`maxOutputSize` is initialized with configuration option …
=> hydra: increase max_output_size from 2GB to 3GB

terraform/dns.tf
For the Summer of Nix Lecture Series we set up an Owncast instance,
currently running under live.bjth.xyz. I'd be better marketing if we ran
that under live.nixos.org instead :).
=> Add live.nixos.org DNS entry

terraform/.terraform.lock.hcl
Without this, `terraform init` fails with:
```
╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/aws v3.56.0: the local package for registry.terraform.io/hashicorp/aws 3.56.0 doesn't match any of the checksums previously recorded in the dependency lock file (this might be because the available checksums are for
│ packages targeting different platforms)
╵
╷
│ Error: Failed to install provider
│ 
│ Error while installing fastly/fastly v0.34.0: the local package for registry.terraform.io/fastly/fastly 0.34.0 doesn't match any of the checksums previously recorded in the dependency lock file (this might be because the available checksums are for
│ packages targeting different platforms)
╵
```
=> Add terraform lock file from bastion

channels.nix
With the branch-off tomorrow the jobsets will come into existance and the channels should follow soon after.
=> channels: Add NixOS 22.11 as beta

terraform/dns.tf
I'm going to decommission this machine pretty soon. Should we perhaps look into creating a more permanent solution for livestreaming?
Ref: https://github.com/NixOS/nixos-org-configurations/pull/213#issuecomment-1191177100
=> Remove live.nixos.org records

delft/hydra-proxy.nix
In 2022 one should not accidentally be on a non-TLS website when just entering "hydra.nixos.org" in the url bar
=> enable TLS redirect for hydra.nixos.org

macs/flake.lock
• Updated input 'nixpkgs':
'github:nixos/nixpkgs/f540aeda6f677354f1e7144ab04352f61aaa0118' (2022-10-26)
→ 'github:nixos/nixpkgs/747927516efcb5e31ba03b7ff32f61f6d47e7d87' (2023-02-07)
---
Most importantly, updates macs relying on this config to nix 2.13.2, which includes a fix for the auto-gc issue that sometimes crops up: https://github.com/NixOS/nix/pull/7542
=> macs/flake.lock: Update

terraform/dns.tf
For Nix's 20th anniversary, the marketing team had the idea to host livestreams like during the Summer of Nix. I've just re-used the server config of the Summer of Nix, but these records were removed back then.
cc: @zimbatm @garbas
=> Add live.nixos.org records

terraform/dns.tf
It would be good to have a place to collect information about Reproducible Builds on Nix. Currently there is https://r13y.com, but it is rather outdated and it would be good to gradually move this to more shared infrastructure so we can collaborate on maintaining it.
This is a first step in that direction, having more up-to-date reports hosted from my uberspace.de account. Next steps might be to generate those reports from nix-community infra and host them on the Nix netlify, but let's take one step at a time.
You can preview the content at https://nix-rb.bzzt.net
=> Introduce reproducible.nixos.org

delft/eris.nix, delft/eris/mjolnir.nix
This will require infra team interaction for deployment (as it will need to be deployed to eris), as well as when there are desired changes in the NixOS configuration.
=> delf/eris: init mjolnir

non-critical-infra/.sops.yaml, non-critical-infra/flake.lock, non-critical-infra/flake.nix, non-critical-infra/hosts/hetzner-01/default.nix, non-critical-infra/modules/first-time-contribution-tagger.nix, non-critical-infra/secrets/first-time-contribution-tagger-env.hetzner01
There is still some stuff to do like adding secret management with something like sops or agenix
I have to push version 1.0.0 of the first-time-contribution-tagger which will add a configuration option to download the cache from the GitHub release so there won't be any imperative steps left for setting this up.
The repo at github.com/janik-Haag/first-time-contribution-tagger will probably be moved to the nix-community name space. 
I also obviously can't test if this deploys fine to the hetzner machine. 
This closes #258
=> non-critical-infra: add first-time-contribution-tagger

terraform/releases.tf
Since we have 28 TB in this bucket, this gives a non-trivial savings.
=> Move releases to Infrequent Access after a year

non-critical-infra/hosts/hetzner-01/default.nix, ssh-keys.nix
Creates the `infra` key list and migrates hetzner-01 to run with it.
The wrong keys were deployed for me, so I had to access the host using the keypair I use for GitHub.
Fetching keys from GitHub is not great for key hygiene and did in fact cause a hash mismatch on Julien's keys.
@JulienMalka Please set up keys in `./ssh-keys.nix`, deploying all 14 keys from GitHub feels wrong.
=> Reuse ssh-keys for non-critical-infra

delft/hydra-proxy.nix
As reported in https://github.com/NixOS/nixos-org-configurations/issues/284 hydra is not currently accessible over ipv6 even though a AAAA record is published.
Apache is currently listening on only ipv4 addresses. This PR explicitly adds `[::]` to the listen address config so that ipv6 will be fully supported.
After change in test vm:
closes #284
=> hydra-proxy: explicitly listen on ipv6 addresses

terraform/cache_inventory.tf
This makes it cheaper to traverse and analyze the S3 list of files.
This will be useful to answer a few questions like:
* what is the oldest file that we have?
* how much data is stored in what time ranges?
* give me the list of all .drv or .narinfo files in the bucket.
* how many files of which type do we have?
* what is the distribution of file sizes?
=> cache: add parquet inventory

terraform-iam/cache.tf, terraform-iam/outputs.tf
Guessing at how things are architectured, lmk if that matches how you want the two Terraform codebases to be split and how you want data to be shared between the two.
Making this a separate PR so that @zimbatm (or someone else) can apply the diff early, and then I have an IAM identity ready to play with for the main change.
Ref #277
```
+ resource "aws_iam_access_key" "fastly-cache-access" {
+ create_date                    = (known after apply)
+ encrypted_secret               = (known after apply)
+ encrypted_ses_smtp_password_v4 = (known after apply)
+ id                             = (known after apply)
+ key_fingerprint                = (known after apply)
+ secret                         = (sensitive value)
+ ses_smtp_password_v4           = (sensitive value)
+ status …
```
=> iam: add new user for fastly<->cache authn

terraform/cache.tf, terraform/dns.tf
Splitting this out into a separate PR like #293 since I don't have permissions to add new TLS subscriptions.
The aim is to copy the current Fastly cache config to cache-staging.nixos.org so we can make sure the authn VCL works before pushing it to the main cache.nixos.org config.
DNS was already pushed:
```
$ host cache-staging.nixos.org
cache-staging.nixos.org is an alias for dualstack.v2.shared.global.fastly.net.
```
cc @zimbatm 
Ref #277
=> dns, fastly: add cache-staging.nixos.org domain + TLS subscription

terraform/cache.tf, terraform/cache/s3-authn.vcl, terraform/locals.tf
This authenticates Fastly requests for cache-staging.nixos.org going to the cache S3 bucket, and sets the request-payer: "requester" header (which might be required if the IAM user is not in the same project as the S3 bucket).
Deployed already and https://cache-staging.nixos.org/nix-cache-info seems to work as expected.
Note that this duplicates the Terraform config for the cache Fastly service, because Terraform is pain and there's no way to e.g. inherit from a resource to apply selective overrides. The only differences between the two services should be:
1. cache.nixos.org -> cache-staging.nixos.org
2. no S3 logging
3. the authn VCL
Ref #277
=> cache-staging: add fastly service configuration and test VCL for authentication

terraform/cache.tf
Ref #277
Configuration already tested to work on cache-staging.
Not applied yet, will push to prod in ~2h if no objection.
=> cache: authenticate Fastly<->S3 requests in preparation for Requester Pays

.github/workflows/terraform-fmt.yml
Attempt at preventing spurious diffs when people like me don't know or forget that `terraform fmt` is a thing :-)
Not technically perfect since it's not using the `terraform` version from nixpkgs or the `flake.lock`, but likely good enough. If it causes problems, we can fix it later.
=> ci: add a "terraform fmt" check on pushes/PRs

delft/hydra.nix
We don't use Cloudfront anymore, and Fastly should be setting the proper CORS headers.
=> hydra: use cache.nixos.org URL for logs instead of raw S3 URLs

terraform/cache.tf
Not applied yet, will apply on 2023-11-04 (Saturday).
```
+ resource "aws_s3_bucket_request_payment_configuration" "cache" {
+ bucket = "nix-cache"
+ id     = (known after apply)
+ payer  = "Requester"
}
Plan: 1 to add, 0 to change, 0 to destroy.
```
Will merge once applied and tested to not explode, filing this PR to get any review feedback prior to applying later this week.
Fixes #277
=> terraform: cache: configure as Requester Pays

terraform-iam/archeologist.tf
This currently only seems accessible from the SSO users, not the instance role.
This will allow automated processing of bucket logs.
See https://cs.tvl.fyi/depot/-/commit/281cb93ba808b73d4ea4ce86f762bbcb504a09da for context.
cc @zimbatm
=> terraform: give archaeologist IAM policy permission to access cache_log bucket

terraform-iam/archeologist.tf
```
commit c483e95aa1841f580e7c58465c3eefa334e3afde
Author: Florian Klink <flokli@flokli.de>
Date:   Sat Nov 11 19:51:58 2023 +0200
terraform-iam: fix listing for nix-cache-logs and others (hopefully)
This adds support for the ListObjects[V2] actions, which should allow
listing the contents in there.
commit 0e8f09c139c80346679d1ac4b49a25b50d895ae0
Author: Florian Klink <flokli@flokli.de>
Date:   Sat Nov 11 19:43:49 2023 +0200
terraform-iam: convert to aws_iam_policy_document
This makes it a bit easier to write these policies. It's a mechanical
conversion from the previous version.
```
=> allow bucket object listing

terraform/cache_log.tf
Since https://cs.tvl.fyi/depot/-/commit/e4adca0880547f2ea825aeec5f64671c6c0324ae the archaeology ec2 instance aggregates logs daily at 3am UTC, so there's no need to keep it around for 120 days.
We can delete it after 30 days, rather than moving it to IA.
Theoretically, we could even delete it after a day or two, but this gives us some slack to notice the job aggregation failed.
cc @zimbatm
=> cache_log: expire bucket logs after 30 days

ssh-keys.nix
Aligning with https://github.com/orgs/NixOS/teams/infra membership.
cc @JulienMalka since this mostly impacts non-critical-infra.
=> ssh-keys: add delroth to infra

delft/eris.nix, delft/haumea.nix
As per #324. This is already how `rhea` is configured.
This configuration is duplicated for now, there are plenty of refactorings to come, but I'm doing that after getting rid of nixops because until then I can't even `nix build` the configs locally without using a nixops version that's not in nixpkgs anymore...
=> eris,haumea: allow infra-core members to SSH without nixops ssh

modules/wireguard-hosts.toml
I decided against adding a port, since my end is floating anyway.
=> wireguard-hosts: add hexa-helix

delft/eris.nix
The way they're set up makes this alert far too noisy and unactionable.
Closes: #331
=> delft/eris: don't alert on space/inode issues on packet nodes

delft/hydra-scaler.nix
It's been commonly hapenning that we spin up many machines but can't keep them occupied due to bottlenecks in the central machine (probably it's mostly the compression of copying-results step)
So let's scale less aggressively and thus waste less.
=> rhea: scale less

non-critical-infra/hosts/caliban.nixos.org/default.nix, non-critical-infra/modules/backup.nix, non-critical-infra/secrets/backup-secret.caliban, non-critical-infra/secrets/storagebox-ssh-key.caliban
Adds a backup module, encapsulating borgbackup, and configures the storagebox we have for caliban.nixos.org.
The backup module will not be enabled until any path is added in to `services.backup.includes`, but I tested it, and it works.
=> non-critical-infra/backup: init and configure on caliban

modules/prometheus/default.nix, modules/prometheus/nixos-exporter.py, modules/prometheus/nixos-exporter/default.nix, modules/prometheus/nixos-exporter/prometheus_nixos_exporter/__main__.py, modules/prometheus/nixos-exporter/pyproject.toml
The output of `nix path-info --json` changed from a list to an object in nix 2.19.0.
Add a simple version detection, so we can support both output formats.
Fixes: #346
=> prometheus-nixos-exporter: add nix 2.19.0 compat

non-critical-infra/hosts/caliban.nixos.org/default.nix, non-critical-infra/modules/vaultwarden.nix, non-critical-infra/secrets/vaultwarden-env.caliban
=> non-critical-infra: vaultwarden init

delft/common.nix, delft/eris-physical.nix, delft/eris.nix, delft/eris/network.nix, delft/haumea-physical.nix, delft/haumea.nix, delft/haumea/network.nix, delft/rhea/configuration.nix, delft/rhea/hetzner.nix, delft/rhea/network.nix, terraform/dns.tf
- Migrates network configuration to networkd 
- Drops udev rules for network interface names, returns to predictable interface names
- Should be impact-free, since we don't match the interface name anyway
- Migrates DNS configuration to resolved
- Moves eris' IPv6 address from the network address
- Sets up IPv6 DNS for eris
=> delft: update network configuration

delft/eris.nix
There might be some initial flakiness due to some badly behaved services, e.g. hydra-scale-equinix-metal, but nothing that we can't silence away and properly fix later.
15m is a very conservative threshold, I'm expecting to push it down at some point once things get more under control.
=> eris: alert on failed systemd services

delft/eris-physical.nix, delft/haumea-physical.nix, modules/common.nix
This removes the deprecation warnings from the nix module. The sandbox config is dropped on purpose, since the sandbox is enabled by default.
=> Migrate nix configuration into nix.settings

modules/prometheus/nixos-exporter/prometheus_nixos_exporter/__main__.py
This allows alerting on when the current-system has a different kernel, than the booted one, which usually indicates we should reboot the machine.
@maralorn originally wanted this, and I proposed we extend the exporter for the benefit of NixOS infra.
```
nixos_current_system_kernel_booted{booted="/nix/store/gp3pl6swvksnj9ws646fnlz553w079pb-linux-6.1.77", current="/nix/store/gp3pl6swvksnj9ws646fnlz553w079pb-linux-6.1.77", instance="eris:9300", job="nixos", role="monitoring"} 1
=> prometheus-nixos-exporter: Expose whether current-system kernel is booted

.github/CODEOWNERS
A bit messy since the directory structure isn't great right now, and I have not tested to check that this actually does what I want it to. But from my reading of the branch protection settings, it should.
cc @JulienMalka - this should allow you to review and merge changes that don't touch the core infra. I kinda wanted to figure this out before we onboard more people :)
-----
Combined with branch protection, this should allow for the following:
- PRs that impact these directories will require approval from at least one core-infra member.
- PRs that do not impact these directories can be approved by anyone who has write access to the repo (incl. non-critical infra members)
- Only core-infra members can push without going through a PR.
=> .github: add CODEOWNERS for core-infra owner parts of the repo

delft/pluto/default.nix, delft/pluto/disko.nix, delft/pluto/grafana.nix, delft/pluto/nixos-metrics.nix, delft/pluto/prometheus/default.nix, delft/secrets.nix, delft/secrets/pluto-backup-secret.age, delft/secrets/pluto-backup-ssh-key.age, modules/backup.nix, modules/common.nix
- sets the mountpoints for prometheus and victoriametrics dataset
- copies the backup module from non-critical-infra
- prepare the backup to the storagebox
- configure backups to include prometheus, grafana, victoriametrics
=> pluto: configure backups

terraform-iam/fastlylog/main.tf
Extracted from #388 since this is already terraform-applied.
=> Fastly logs bucket policy to give the fastly-log-processor user access

delft/flake.lock, delft/flake.nix
Provide an output that translates nixosConfigurations to a colmena- compatible output.
Colmena provides a convenient wrapper around building and deploying machines, than the bare nixos-rebuild we had been using up until now.
=> delft: allow deployment through colemena

terraform/cache.tf, terraform/channels.tf, terraform/locals.tf, terraform/nixpkgs-tarballs.tf, terraform/releases.tf
We were previously always shielding via the Virginia POP which is closest to us-east-1. However the S3 buckets for releases.nixos.org and tarballs.nixos.org are hosted in eu-west-1 (Dublin). Let's save on some transatlantic roundtrips, and maybe even improve #212.
=> fastly: use shielding POPs that match backend location

non-critical-infra/flake.lock
Not applied yet: 
```
umbriel.nixos.org | would stop the following units: audit.service, growpart.service, kmod-static-nodes.service, logrotate-checkconf.service, mjolnir.service, mount-pstore.service, network-local-commands.service, nscd.service, pantalaimon-mjolnir.service, systemd-modules-load.service, systemd-oomd.service, systemd-oomd.socket, systemd-sysctl.service, systemd-timesyncd.service, systemd-udevd-control.socket, systemd-udevd-kernel.socket, systemd-udevd.service, systemd-vconsole-setup.service, zfs-mount.service, zfs-share.service, zfs-zed.service
umbriel.nixos.org | would NOT stop the following changed units: getty@tty1.service, serial-getty@ttyAMA0.service, serial-getty@ttyS0.service, systemd-fsck@dev-disk-by\x2dpartlabel-disk\x2dmain\x2desp.service, …
```
=> non-critical-infra: update flake inputs

delft/pluto/prometheus/alertmanager.nix
This patch is a small change in the go-neb configuration to remove some clutter from the [infra alerts room](https://matrix.to/#/#infra-alerts:nixos.org). Since some alerts don't include a link to a Grafana dashboard, we can only print that part of the message when it's relevant.
I haven't tested this with an actual go-neb instance + alertmanager, but only a Go templating tester and seems to work fine.
=> go-neb: Only show Grafana link when applicable

terraform/dns.tf
The Hydra instance at hydra.ngi0.nixos.org is being sunset and will be replaced by a buildbot instance, see https://github.com/ngi-nix/ngipkgs/issues/200. The CNAME will be removed once we've moved to buildbot.
Some context:
- The host config for hydra.ngi0.nixos.org was moved from this repo to [ngi-nix/ngi0-infra](https://github.com/ngi-nix/ngi0-infra), see https://github.com/NixOS/infra/issues/326
- We're now moving it from there to [ngi-nix/ngipkgs](https://github.com/ngi-nix/ngipkgs), see https://github.com/ngi-nix/ngipkgs/pull/201
cc @Erethon
=> dns: `hydra.ngi0, buildbot.ngi → makemake`

delft/hydra.nix
Nobody should ever need to directly log into these. The infra team already has root access and can switch to these users as needed.
=> delft/hydra: remove authorized_keys for hydra users

terraform/dns.tf
While reviewing https://github.com/ngi-nix/ngipkgs/pull/201/ I noticed that `makemake.nixos.org` doesn't resolve to anything but it's used as a CNAME after #419. This is a typo I believe and it should be `makemake.ngi.nixos.org`. This PR fixes that.
CC @lorenzleutgeb who knows more about this
=> dns: Fix typo in makemake hostname

delft/pluto/prometheus/exporters/blackbox.nix
A couple of days ago `wiki.nixos.org` was [down for some minutes](https://matrix.to/#/!JrBtSIugVadKwbhvCc:matrix.org/$MYx0CTR3LL294KETwloJws1BPn7T0zAFnlgHILnR51o?via=nixos.org&via=matrix.org&via=fairydust.space). This patch adds `wiki.nixos.org` to the list of monitored domains via blackbox exporter, similarly to what we do for the rest of the nixos.org websites. While it won't alert people [1] if it happens again, at the very least it will provide some insight and help debug things if they misbehave again.
[1]: There are currently no alerts for a *.nixos.org website being down in general.
=> prometheus: Monitor HTTP status of wiki.nixos.org

delft/rhea/configuration.nix
Three months ago the zram size config went from 50% to 80%, but now it doesn't seem enough again.
=> rhea: more zramSwap, again

delft/pluto/prometheus/default.nix, delft/pluto/prometheus/exporters/matrix-synapse.nix, non-critical-infra/flake.lock, non-critical-infra/hosts/caliban.nixos.org/default.nix, non-critical-infra/modules/backup.nix, non-critical-infra/modules/element-web.nix, non-critical-infra/modules/matrix-synapse.nix, non-critical-infra/modules/mjolnir.nix, non-critical-infra/modules/nginx.nix, non-critical-infra/modules/postgresql.nix, non-critical-infra/secrets/matrix-synapse-secrets.caliban, non-critical-infra/secrets/matrix-synapse-signing-key.caliban, terraform/dns.tf
Draft of the matrix-synapse deployment.
Does not yet build, because I'm waiting on UDS support for the synapse listeners, which people are currently actively working on.
- Generic nginx module
- Generic PostgreSQL module with backup integration
- Matrix Synapse module
- Promtheus scraping for Synapse
Depends on
- #345
- https://github.com/NixOS/nixpkgs/pull/286172
Follow-up:
- https://github.com/NixOS/nixos-homepage/pull/1218
=> matrix-synapse: init on caliban

delft/haumea/zrepl.nix
- 3x5m is not actionable since we often take more than 15 minutes to actually notice any issue
- 20x5m is a lot of write churn on the backup target, which is currently only my personal NAS
- 52x1w already offers 52 weekly backups, so 120x3w goes back 6 years and overlaps 17 times with 52x1w. Hopefully we don't need to restore data that is older than 1y.
=> haumea/zrepl: reduce number of snapshots

delft/haumea/postgresql.nix
JIT was previously enabled in the configuration, but the package did not
have support for it.
Disables full page writes, as they are unnecessary on ZFS.
=> haumea/postgresql: use jit package, disable full page writes

delft/pluto/prometheus/default.nix, delft/pluto/prometheus/exporters/zfs.nix, modules/prometheus/default.nix
The hope is that we gain more insight into ZFS dataset usage over time.
Grafana dashboard hopefully upcoming in https://github.com/pdf/zfs_exporter/issues/21
=> delft: set up and scrape prometheus-zfs-exporter

delft/haumea/zrepl.nix
Creating a checkpoint flushes all memory to disk, and applies all WAL files to persistent storage, forward-paying the cost of WAL replay, but on the other hand making snapshots much cheaper.
https://zrepl.github.io/master/configuration/snapshotting.html#job-hook-type-postgres-checkpoint https://www.postgresql.org/docs/current/sql-checkpoint.html
https://www.postgresql.org/docs/current/wal-configuration.html
Whether we should do this is debatable, but the linked documentation should be studied in full, before we make a decision.
=> haumea/zrepl: create pg checkpoint before taking snapshot

docs/inventory.md
Hello there 👋!
The NixOS wiki is in the process of migrating from https://nixos.wiki to https://wiki.nixos.org.
You can find more information about it [here](https://github.com/NixOS/foundation/issues/113).
You seem to be using the old link in your repository, which is why we send you this PR.
If you feel like this is not correct or have any questions, feel free to [get in touch with us](https://github.com/NixOS/nixos-wiki-infra/issues/105).
Have a great day,
-- The NixOS Wiki-Team ❄️
=> Update NixOS Wiki link

build/haumea/postgresql.nix, build/haumea/zrepl.nix, build/haumea/zrepl.yml
Reduce snapshot count.  We repeatedly run out of space on Haumea.
=> haumea/zrepl: reduce snapshot count

macs/flake.lock, macs/nix-darwin.nix
```
• Updated input 'darwin':
'github:LnL7/nix-darwin/87b9d090ad39b25b2400029c64825fc2a8868943' (2023-01-09)
→ 'github:LnL7/nix-darwin/7e08a9dd34314fb8051c28b231a68726c54daa7b' (2024-07-31)
• Updated input 'nixpkgs':
'github:nixos/nixpkgs/1e383aada51b416c6c27d4884d2e258df201bc11' (2023-03-08)
→ 'github:nixos/nixpkgs/c3392ad349a5227f4a3464dce87bcc5046692fce' (2024-07-31)
```
This should bring us to nix 2.18.5.
=> macs/flake.lock: Update and unpin nix.package

terraform/nixpkgs-tarballs.tf
we don't the fancy UI, json logs are enough for our use case. Also this way we don't need to create a role.
=> terraform/nixpkgs-tarballs: use cloudtrails without cloudwatch

README.md
Hi!
While I was browsing the repo, I ended up confused about the dates of the meetings (as June 11, 2024 was a Tuesday). The changes I propose make these dates fixed in time. I hope that they will lead to a more understandable schedule.
January 11th is just an informed guess, so please feel free to correct me.
Cheers!
=> README: make meeting dates more clear

non-critical-infra/README.md, ssh-keys.nix
I'm going to be working on <https://github.com/NixOS/infra/issues/485>. This will give me the power to do most of the work there, except for deploying the relevant DNS changes with Terraform.
=> Give myself access to non-critical infra

macs/README.md, macs/nix-darwin.nix
Tested on intense-heron, where I also found a nix-2.13.3 profile which overruled the nix-darwin maintained nix version.
```
sh-3.2# nix profile list
0 - - /nix/store/pl497357lkfpvdr8v4pfan16k7jna2l2-nss-cacert-3.83
1 - - /nix/store/8w0v2mffa10chrf1h66cbvbpw86qmh85-nix-2.13.3
sh-3.2# nix profile remove 1
removing 'nix'
sh-3.2# nix --version
nix (Nix) 2.18.8
```
=> macs: update deployment hints

build/datadog/hydra.py, build/pluto/prometheus/exporters/channel-exporter.py, build/pluto/prometheus/exporters/hydra-queue-runner-reexporter.py, formatter/flake-module.nix, hydra-packet-importer/default.nix, macs/nix-darwin.nix
NOTE: This PR depends on https://github.com/NixOS/infra/pull/496. Please review/merge that PR before this one.
All I did here was:
- Add `ruff-format`
- Run `nix fmt`
- Remove `black` stuff from `hydra-packet-importer/`
Why? I'm going to add a helper script to
https://github.com/NixOS/infra/pull/495#issuecomment-2443284452, and I'd
like to write it in Python and have autoformatting.
=> Add ruff-format to treefmt (to format Python files)

build/datadog/hydra.py, build/pluto/prometheus/exporters/channel-exporter.py, build/pluto/prometheus/exporters/hydra-queue-runner-reexporter.py, flake.lock, flake.nix, hydra-packet-importer/import.py, modules/prometheus/nixos-exporter/prometheus_nixos_exporter/__main__.py, non-critical-infra/flake-module.nix, non-critical-infra/hosts/umbriel.nixos.org/README.md, non-critical-infra/hosts/umbriel.nixos.org/default.nix, non-critical-infra/modules/mailserver/README.md, non-critical-infra/modules/mailserver/default.nix, non-critical-infra/modules/mailserver/mailing-lists.nix, non-critical-infra/packages/encrypt-email-address/default.nix, non-critical-infra/packages/encrypt-email-address/encrypt-email-address.py, non-critical-infra/secrets/jfly-email.umbriel, pyproject.toml, terraform/dns.tf
This is part 1 of https://github.com/NixOS/infra/issues/485
=> Add simple-nixos-mailserver to umbriel

macs/nix-darwin.nix, non-critical-infra/hosts/umbriel.nixos.org/README.md, terraform/dns.tf
While working on
<https://gitlab.com/simple-nixos-mailserver/nixos-mailserver/-/merge_requests/344>, I accidentally deleted the `DKIM` key on `umbriel` :(
=> Update DKIM key for test mailserver

channels.nix
*To be released on Saturday, November 30th.*
=> channels: Promote NixOS 24.11 to stable

terraform/dns.tf
Unfortunately, this doesn't play nicely with mailing lists and some receiving mail architectures.
See
https://gitlab.com/simple-nixos-mailserver/nixos-mailserver/-/issues/302 for a complete explanation.
=> Use a looser SPF record

build/.envrc, channels.nix, flake.lock, flake.nix, non-critical-infra/.envrc, non-critical-infra/modules/vaultwarden.nix, terraform-iam/.envrc, terraform/.envrc, terraform/flake-module.nix
=> Update to NixOS 24.11

build/common.nix, build/flake.nix, build/haumea/postgresql.nix, build/hydra-proxy.nix, build/hydra.nix, build/mimas/boot.nix, build/mimas/default.nix, build/mimas/disko.nix, build/mimas/network.nix, build/pluto/prometheus/exporters/nixos.nix, build/pluto/prometheus/exporters/node.nix, build/pluto/prometheus/exporters/zfs.nix, build/rhea/configuration.nix, build/secrets.nix, build/secrets/hydra-aws-credentials.age, macs/nix-darwin.nix, modules/wireguard-hosts.toml, ssh-keys.nix, terraform/dns.tf
Work in progress configuration for a successor to rhea, because the machine cannot keep up with the compression workload by the large number of builders we employ.
The plan is for an [AX162-R](https://www.hetzner.com/dedicated-rootserver/ax162-r/configurator/#/) at Hetzner.
TODO:
- Check we have all relevant configs and secrets from rhea
=> build: init mimas

build/pluto/prometheus/exporters/blackbox.nix, build/pluto/prometheus/exporters/node.nix, terraform/dns.tf
This is a PR to setup the [Nixpkgs Security Tracker](https://github.com/Nix-Security-WG/nix-security-tracker) on the nixos.org domain.
On the surface this PR is very simple as it only:
- Creates a new A record for `tracker.security.nixos.org` that points to a Hetzner Cloud VM host (188.245.41.195)
- Adds monitoring for this domain
The VM is part of the `nixpkgs-security-tracker` Hetzner Cloud project which @zimbatm gave me access to a while ago.
The configuration of this host will eventually be [here](https://github.com/Nix-Security-WG/nix-security-tracker/tree/main/infra), but please note that [this draft PR](https://github.com/Nix-Security-WG/nix-security-tracker/pull/454) contains the important bits for now and isn't merged yet as it depends on having a .nixos.org domain for the host. …
=> Init security tracker domain and monitoring

macs/mac-exec
Adds a small wrapper script I use to execute commands on all macs in parallel.
=> macs: add small wrapper to execute calls on all macs

build/hydra.nix, build/pluto/prometheus/exporters/node.nix, builders/boot/efi-grub.nix, builders/common/hardening.nix, builders/common/network.nix, builders/common/nix.nix, builders/common/node-exporter.nix, builders/common/ssh.nix, builders/common/system.nix, builders/common/tools.nix, builders/common/update.nix, builders/common/users.nix, builders/disk-layouts/efi-zfs-raid0.nix, builders/flake-module.nix, builders/instances/elated-minsky.nix, builders/instances/goofy-hopcroft.nix, builders/instances/sleepy-brown.nix, builders/network/autoconfig.nix, builders/profiles/hetzner-ax101r.nix, builders/profiles/hetzner-rx220.nix, flake.nix, terraform/dns.tf
With the following ideas:
- Use ZFS for RAID0
- Use tmpfs for /tmp and host build directories in RAM
- Run all builds in cgroups
- Updates and reboots using `system.autoUpgrade`
- Network autoconfiguration
=> builders: init profile based builder configuration

build/hydra.nix
The new ISOs will have the LTS and latest kernel integrated as specialisations, which makes them about 205 MB larger on x86-64-linux.
What we get out of this is one less separate ISO for x86_64-linux and aarch64-linux we need to create and store.
=> hydra: increase max_output_size

.github/workflows/ci.yml, macs/common.nix, macs/flake-module.nix, macs/mac-update, macs/profiles/m1.nix, macs/profiles/m2.large.nix
We need jobs with larger core counts to accomodate big build jobs, that would otherwise timeout.
=> macs: configure cores/jobs per profile

builders/common/nix.nix
Deployed on ~~`sleepy-brown`~~ `elated-minsky` for testing, and I don't think this is controversial anyway.
=> builders: add the "benchmark" feature on their nix side

terraform/cache-staging/diagnostic.sh, terraform/cache/diagnostic.sh
This fixes https://github.com/NixOS/infra/issues/537
Demo:
```
$ terraform/cache/diagnostic.sh
...
> curl_test -6 https://cache.nixos.org/
Pasted at: https://termbin.com/8p7n
```
=> Switch from `ix` to `termbin`

flake.lock, flake.nix
• Updated input 'darwin':
'github:LnL7/nix-darwin/ba9b3173b0f642ada42b78fb9dfc37ca82266f6c' (2025-01-05)
→ 'github:LnL7/nix-darwin/cae8d1c4a3bd37be5887203fe3b0c3a860c53a07' (2025-01-21)
=> flake.nix: Update nix-darwin branch

terraform/dns.tf, terraform/netlify_sites.tf
Done as part of https://github.com/NixOS/nixos-summer/issues/46 and https://github.com/NixOS/nixos-homepage/pull/1559. We no longer need `summer.nixos.org` to be hosted by Netlify, instead it will now point to `makemake.ngi.nixos.org` and only serve some [redirects](https://github.com/ngi-nix/ngipkgs/pull/476) to the relevant blog posts, reports, etc.
cc @fricklerhandwerk
=> dns: Move summer.nixos.org away from netlify

builders/common/nix.nix
This was introduced [without any linked discussion/explanation](https://github.com/NixOS/infra/pull/524), so let's document it now. I asked about the reason on Matrix and [was told](https://matrix.to/#/!RROtHmAaQIkiJzJZZE:nixos.org/$_zH2bGUSUChkNFNjxwpCeWL_OVa-9XELobMhsqCOinE?via=nixos.org&via=matrix.org&via=nixos.dev) the answer by @K900. Though I'm leaving this as a draft until we actually know what the segfault was.
Nothing against Lix, but on the Nix Hydra we should really be dog-fooding Nix. Imo if there's a bug, it should be reported so it can be fixed before upgrading.
Pinging @NixOS/nix-team in case anybody has a clue what the problem could be, and how it could be fixed.
Note that evals on the coordinator still use Nix, it's only builder machines that are using Lix for now.
=> Document why Lix is used on builders

build/pluto/prometheus/exporters/blackbox.nix
Previously, we had `instance=mail-test.nixos.org`, but this doesn't tell us the host this MX record points at. Now we have a host as well (such as `host=umbriel.nixos.org`).
=> Add host label to `smtp_starttls` scrapes

build/flake.nix, flake.lock, flake.nix, non-critical-infra/flake-module.nix
the only place we were using this, was for the devshell.
But it's not really clear to me if we still need this?
cc @jfly
=> no longer depends on nixpkgs-unstable

terraform/dns.tf
Per @zimbatm:
> It's a legacy thing. Gandi used to offer free email and then removed
> it.
=> Remove gandi.net from our SPF record

terraform/channels.tf
This is part of another PR over in NixOS/nixos-channel-scripts that implements the precomputed x-amz-meta-link header. For the motivation behind this change look there (https://github.com/NixOS/nixos-channel-scripts/pull/76).
Hydra executes mirror-nixos-branch.pl when a given channel advances. Thus, we need some sort of fallback to handle channels which have long been EOL. A fallback also allows this change to be deployed in any order and over the span of multiple days.
Our default mode of operation is simply renaming the precomputed "x-amz-meta-link" header created by the script to "link", if it exists. Note that we cannot use "link" directly because AWS S3 does not allow it.
As a fallback we take the "location" header (which always exists) and template it into "link".
This lacks …
=> fastly: implement "Lockable HTTP Tarball Protocol" (Flakes) for channels.nixos.org

build/common.nix, modules/common.nix
looks like nixos-24.11-small actually doesn't include emacs, so we sometimes end up building this in our CI.
Since we no longer have any emacs user in the team, we can drop it.
=> drop emacs

terraform/dns.tf
As part of https://github.com/ngi-nix/summer-of-nix/issues/179 we want ngi.nixos.org to point to GitHub Pages so we can serve a landing page for users via GitHub.
I haven't tested this, as I can't run a terraform/tofu plan, but it passes `tflint` and `fmt`.
I've hardcoded the GitHub Pages IPs, which I don't forsee changing soon, but if we prefer a dynamic approach let me know and I'll rewrite this to use the [GitHub Provider](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/ip_ranges#pages_ipv4-1) to automatically pull these IPs via a data source.
=> dns: Point ngi.nixos.org to GitHub Pages IPs

build/pluto/prometheus/exporters/blackbox.nix
Today, our MX record point at `mx*.improvmx.com`. Soon, we'll switchover to `umbriel.nixos.org` as our mailserver. It's useful to monitor `nixos.org` regardless of who the underlying host is. In addition, it's useful right now to monitor our new mailserver explicitly (which we can remove once we've switched over).
=> Monitor STMP on umbriel explicity, as well as `nixos.org`

.github/workflows/ci.yml
We rather want builds to be cached and not having to be repeated.
=> github ci: disable fail-fast

build/pluto/prometheus/exporters/blackbox.nix
We have 2 mailservers (ImprovMX and SNM on umbriel), and our probes for both of them are failing:
This scrape is failing. [link](https://prometheus.nixos.org/targets?search=&scrapePool=blackbox-smtp_starttls_umbriel):
We're doing a HTTP(S) check when we should be doing a SMTP check.
Fix: use correct scraper module name.
This scrape is succeeding, but returning a failure. See [link](https://prometheus.nixos.org/graph?g0.expr=probe_success%7Bjob%3D%22blackbox-smtp_starttls%22%7D%20%3D%3D%200&g0.tab=1&g0.display_mode=lines&g0.show_exemplars=0.g0.range_input=1h).
Fix: don't assume mailserver greeting includes "ESMTP"
=> fix mailserver probes

build/pluto/prometheus/exporters/blackbox.nix
A few things here:
1. Increase the `stmp_starttls` timeout. We're seeing probes sporadically fail against ImprovMX with "i/o timeout". (see logs below)
2. Add missing port for probing `umbriel` (oops).
3. Also alert on `umbriel` probe failures.
ImprovMX probe logs:
```
ts=2025-03-10T16:27:37.785620787Z caller=main.go:190 module=smtp_starttls target=mx2.improvmx.com:25 level=info msg="Beginning probe" probe=tcp timeout_seconds=5
ts=2025-03-10T16:27:37.785744902Z caller=tcp.go:40 module=smtp_starttls target=mx2.improvmx.com:25 level=info msg="Resolving target address" target=mx2.improvmx.com ip_protocol=ip6
ts=2025-03-10T16:27:37.823984377Z caller=tcp.go:40 module=smtp_starttls target=mx2.improvmx.com:25 level=info msg="Resolved target address" target=mx2.improvmx.com …
```
=> More mailserver probe fixes

terraform/dns.tf
Follow up on #572. This is needed to verify the domain ownership on GitHub, sorry for not realizing sooner and having this as part of #572.
=> dns: Add GitHub TXT verification for ngi.nixos.org

non-critical-infra/hosts/umbriel/README.md, non-critical-infra/modules/mailserver/default.nix, non-critical-infra/packages/encrypt-email/encrypt-email.py, non-critical-infra/secrets/nixos.org.mail.key.umbriel, terraform/dns.tf
Depends on <https://github.com/NixOS/infra/pull/571/>. Please review/merge that PR first.
Once this change is deployed, we should be able to start sending test emails from `@nixos.org` email addresses using umbriel. I updated our SPF record in a way such that it should allow umbriel without breaking our existing email sending capabilities (ImprovMX and gandi.net).
This does *not* change our MX (yet): ImprovMX will still be receiving emails send to `nixos.org`. To verify that we can receive emails sent to `nixos.org` addresses, I plan to edit `/etc/hosts` on my personal mailserver and send some test emails. Do folks have better ideas for testing this out?
=> Allow umbriel to send emails as nixos.org

non-critical-infra/hosts/umbriel/default.nix
Before:
```console
$ nix eval .#nixosConfigurations.umbriel.config.system.build.toplevel
evaluation warning: Using 'routeConfig' is deprecated! Move all attributes inside one level up and remove it.
evaluation warning: Using 'routeConfig' is deprecated! Move all attributes inside one level up and remove it.
«derivation /nix/store/yp4hjn03fw471l7nz2c0h26vhxjgyx4k-nixos-system-umbriel-24.11.20250308.52e3095.drv»
```
After:
```console
$ nix eval .#nixosConfigurations.umbriel.config.system.build.toplevel
warning: Git tree '/home/jeremy/src/github.com/NixOS/infra' is dirty
«derivation /nix/store/yp4hjn03fw471l7nz2c0h26vhxjgyx4k-nixos-system-umbriel-24.11.20250308.52e3095.drv»
```
=> Fix evaluation warning about `routeConfig` on `umbriel`

build/pluto/prometheus/exporters/domain.nix
This fixes the false positive we got on the [NixOS Infra Alerts channel today](https://matrix.to/#/!QLQqibtFaVtDgurUAE:nixos.org/$Jrcfj08eep_DZOaZYVNSU90rQ9nF8jbwvT7hcqqEwx0?via=nixos.org&via=matrix.org&via=nixos.dev).
It also adds an alert for when a whois query fails for more than three hours. I chose three hours as a heuristic based on the duration of previous failures of this probe, so that we don't get false positives when there's a blip in a WHOIS server.
=> prometheus: Catch false positive on domain expiry

build/pluto/prometheus/exporters/domain.nix
Today we hit a stretch of over 3 hours where we could not successfully query `nix.ci`. Let's bump to a full day and see if we get that unlucky in the future.
=> Increase `for` for `DomainProbeFailure`

terraform/dns.tf
=> dns: add Apple domain verification record

non-critical-infra/modules/mailserver/mailing-lists.nix, non-critical-infra/packages/encrypt-email/encrypt-email.py, non-critical-infra/secrets/ngi-nixos-org-email-login.umbriel
This PR:
1) Updates the python encrypt-mail helper script to make instructions a bit more clear and fix some file paths.
2) Adds a login account for the ngi@nixos.org email address.
=> Add NGI smtp password and update help text on encrypt-mail.py

.github/workflows/dns-apply.yml, .github/workflows/dns-preview.yml, dns/nixos.org.js
Was missed, because the CI didn't trigger.
=> dns: drop final trailing comma in nixos.org zone

build/pluto/prometheus/exporters/node.nix
This doesn't make a material difference (the only value for `diskSelector` is `/`, which we were already using here), but somebody went to the effort to put this in a variable, so IMO we should be consistent about using it.
An alternative would be to just inline the mountpoint everywhere. Let me know what you prefer.
=> Use `diskSelector` variable

build/pluto/prometheus/exporters/node.nix
(continuation of https://github.com/NixOS/infra/pull/550)
IIUC, this doesn't change the behavior of this query at all (Prometheus will still only pick values for `node_filesystem_files_free` and `node_filesystem_files` where all the labels match), but perhaps makes it cleaner to read.
I'm extremely new to PromQL, and I'm mostly filing this as a learning opportunity. Are there best practices around this sort of thing? Do we like the way this was written, and should I change our other expressions ot match (some of the other expressions use `${diskSelector}` twice).
=> nit: add missing `diskSelector` to `node_filesystem_files_free`

non-critical-infra/modules/mailserver/mailing-lists.nix
This is part of the cleanup here: https://github.com/NixOS/infra/issues/587
=> Remove testing mail accounts

.github/workflows/ci.yml, .github/workflows/dns-apply.yml, .github/workflows/dns-preview.yml, .github/workflows/zizmor.yml, flake.lock, flake.nix
Inspired by https://github.com/NixOS/nixpkgs/pull/396451.
Our security posture needs to be at least as good as that of nixpkgs, if not better :wink:
=> Use zizmor to lint GitHub action workflows

flake.lock, flake.nix
This should unblock updates again.
=> Pin nix-eval-jobs for compatibility with our hydra version

build/pluto/prometheus/exporters/blackbox.nix, dns/nixos.org.js, non-critical-infra/modules/mailserver/README.md
This reverts commit e47fbe09e3592bd56c040ee2da718e50547c2eea.
We received a report of delivery issues:
https://github.com/NixOS/infra/issues/485#issuecomment-2784985232.
I'm not sure how long it will take to root cause this issue and fix it. I propose that we roll back for now.
=> Revert "Switch our MX record(s) from ImprovMX to `umbriel.nixos.org`"

build/common.nix, build/flake-module.nix, flake.lock, flake.nix
The master branch has caught up with the patches we've been carrying for the last 12 months or so. We also start following the nix-eval-jobs version pinned in hydra, so that we stay compatible.
```
• Updated input 'hydra':
'github:NixOS/hydra/c3b6e7b425325b2ea65a0ed638c5913ac32d1a28' (2025-02-16)
→ 'github:NixOS/hydra/1c52c4c0ed596ea71de370562ed5af1604bd2183' (2025-04-07)
• Removed input 'hydra/libgit2'
• Updated input 'hydra/nix':
'github:NixOS/nix/a7fdef6858dd45b9d7bda7c92324c63faee7f509' (2024-09-19)
→ 'github:NixOS/nix/a4962f73b5fc874d4b16baef47921daf349addfc' (2025-04-07)
• Removed input 'hydra/nix/libgit2'
• Updated input 'hydra/nix-eval-jobs':
follows 'nix-eval-jobs'
→ 'github:nix-community/nix-eval-jobs/cba718bafe5dc1607c2b6761ecf53c641a6f3b21' …
```
=> flake.nix: Track hydra master branch

non-critical-infra/modules/mailserver/default.nix, non-critical-infra/modules/mailserver/postsrsd.nix, non-critical-infra/secrets/postsrsd-secret.umbriel
We had deliverability issues when forwarding mail to other domains (if the domain of the email we were forwarding had a strict SPF policy, the receiving mailserver would drop it due to SPF fail). See https://github.com/NixOS/infra/issues/485#issuecomment-2787490679 for details.
=> fix(mailserver): enable Sender Rewriting Scheme (SRS) on umbriel

dns/nixos.org.js
The Nix@NGI team plans to survey authors of NGI funded projects. [CryptPad](https://github.com/cryptpad/cryptpad) was selected as the software to use for the survey, so this PR adds two CNAMEs pointing to `makemake.ngi.nixos.org` in order to setup a CryptPad instance there.
=> dns: Add cryptpad(-sandbox).ngi.nixos.org

.github/workflows/dns-apply.yml, .github/workflows/dns-preview.yml, dns/creds.json, dns/dnsconfig.js, dns/nixos.org.js
ALIAS at the domain apex, CNAME for everything else.
=> dns: prepare Gandi migration

build/hydra.nix, build/pluto/prometheus/exporters/node.nix, build/pluto/prometheus/exporters/rasdaemon.nix, builders/flake-module.nix, builders/instances/hopeful-rivest.nix, builders/profiles/hetzner-rx170.nix, dns/nixos.org.js
RX170 builder that up until now was running unmanaged.
=> builders: adopt hopeful-rivest

dns/dnsconfig.js, dns/nixcon.org.js, non-critical-infra/modules/mailserver/default.nix, non-critical-infra/modules/mailserver/mailing-lists.nix, non-critical-infra/secrets/nixcon.org.mail.key.umbriel
Migrates the DNS for nixcon.org to Gandi and management via dnscontrol through this repo.
Sets up mailing through umbriel.nixos.org and migrates some aliases, that are up for debate.
- orgateam@: primary contact address, currently nixcon@nixos.org
- foundation@ : does it make sense to still have that when the same name @nixos.org exists?
- volunteers@: unclear
- 2024@, 2024cfp@: are they still required? @Lassulus
- 2023@ was in Darmstadt and I can guarantee we don't require them any more
- 2022@ is even older, so I'm dropping it as well
Additionally, they all point to the same Google Group that I'm not sure gets used any more.
cc @infinisil
=> dns: migrate nixcon.org and set up mailing

non-critical-infra/modules/mailserver/mailing-lists.nix
Need an email for pretalx and we don't want to use the main one. Discussed in the NixCon org meeting from 2025-04-10
Ping @ra33it0, @ners, @Lassulus, @a-kenji
=> Add nixcon CFP email

dns/nixos.org.js
For the record: I don't feel super strongly about this, and would be happy to close this unmerged. I wanted to file this to continue the discussion started on https://github.com/NixOS/infra/pull/509, when I was young and knew nothing about SRS.
Note: we still have 3 other `~all` SPF records (discourse, caliban, wiki). I imagine they could also get the same treatment if we want to be strict.
<hr>
This (effectively) reverts d65e24dd13b5336eac7f2cabdef577f9a7213fb5.
If you're sending emails to mailing lists that don't implement Sender Rewriting Scheme (SRS) then you might want to avoid using `-all`. IMO, this really is indicative of problem elsewhere. See https://gitlab.com/simple-nixos-mailserver/nixos-mailserver/-/issues/302 for details.
=> [DO NOT MERGE UNTIL 2025-04-17] Use stricter SPF records

build/hydra-proxy.nix, build/pluto/prometheus/default.nix, build/pluto/prometheus/exporters/anubis.nix
=> hydra-proxy: replace abuse handling with anubis

build/hydra.nix
Enable the nix integrated index-debuginfo functionality, which should allow work to remove the index-debuginfo code from channel scripts.
Closes: #484
=> hydra: enable index-debug-info

builders/common/tools.nix
Helpful when inspecting a builder for running builds and related processes.
=> builders: install nix-top

README.md
I now have access to the nixos.org Google Calendar. Hopefully this will help with off-by-one confusion about which Thursday is the day we meet.
I also believe the time was actually wrong before: AFAIK, there is no place on earth that observes CET year round (Zurich switches between CET and CEST).
Full disclosure: I basically copied this wording from the [nix formatting team
readme](https://github.com/NixOS/nixfmt/blob/master/team/README.md).
=> Add info about the team meeting

build/pluto/prometheus/alertmanager.nix
We provide this service only to the alertmanager on the same box anyway.
cc #549
=> go-neb: bind to localhost

channels.nix
Part of the release process.
Please wait for the 25.05 jobsets to be created tho.
=> channels: Add NixOS 25.05 as beta

dns/nixcon.org.js
On behalf of the Nixcon organiser team. We're deploying a web server at `ners.ch` that will check if a given contributor is eligible for a free ticket voucher.
Please squash when merging.
=> Create CNAME for 2025 voucher check

dns/nixcon.org.js
On behalf of the Nixcon organiser team. The Cloudflare setup in front of `ners.ch` isn't behaving as expected. We'll point at a different subdomain instead.
=> dns: update voucher.nixcon.org cname

build/hydra.nix, flake.lock
• Updated input 'hydra':
'github:NixOS/hydra/183bc39d1af3e29c837b829c8f905d4833d8b8a6' (2025-05-09)
→ 'github:NixOS/hydra/35c9264306b0972d19b26320017e0cdba128e878' (2025-05-23)
=> hydra: update and migrate away from legacy gc- prefixed options

terraform-iam/archeologist.tf
The main change is to give them read-only access to the main s3://nix-cache/ on top of the side ones.
The profile had two sid with overlapping permissions, so I removed one side.
Finally, we also given them access to CloudWatch metrics so they can see the bucket sizes.
=> terraform-iam: tune archeologist permissions

build/hydra-proxy.nix, build/pluto/prometheus/default.nix, build/pluto/prometheus/exporters/anubis.nix
=> Reapply "hydra-proxy: replace abuse handling with anubis"

dns/nixos.org.js, terraform/gh-releases.tf
• Add Fastly CDN service for gh-releases.nixos.org to provide friendly URLs for GitHub releases
URL mapping examples:
- gh-releases.nixos.org/nix/0.27.0/
nix-installer.sh  → github.com/NixOS/experimental-nix-installer/releases/download/0.27.0/
nix-installer.sh
- gh-releases.nixos.org/patchelf/0.18.0/patchelf-x86_64-linux → github.com/NixOS/patchelf/releases/download/0.18.0/patchelf-x86_64-linux
=> Fastly configuration for gh-releases.nixos.org

build/pluto/prometheus/alertmanager.nix
When binding to localhost I introduced a typo in the port number which broke the alerting pipeline.
=> go-neb: fix port

modules/tarball-mirror.patch
With NixOS 25.05 there is no nix_2_18 anymore and now we're on an newer version and the perl bindings changed.
=> tarball-mirror: apply github.com/NixOS/nixpkgs/pull/361700

dns/nixos.org.js, terraform/artifacts.tf
This renames the GitHub releases proxy service to use a more generic name that better reflects its purpose as a general artifacts CDN.
Changes:
- Renamed DNS records from gh-releases to artifacts
- Updated ACME challenge CNAME to match Terraform output
- Renamed terraform/gh-releases.tf to terraform/artifacts.tf
- Updated all references in Terraform configuration
The service continues to proxy GitHub releases for NixOS projects through Fastly CDN with IPv6 support.
=> Rename gh-releases.nixos.org to artifacts.nixos.org

build/hydra-proxy.nix
Put a rate limit on per source adress requests to hydra-server
> Excessive requests are delayed until their number exceeds the maximum burst size in which case the request is terminated with an [error](https://nginx.org/en/docs/http/ngx_http_limit_req_module.html#limit_req_status).
https://nginx.org/en/docs/http/ngx_http_limit_req_module.html
=> hydra-proxy: limit per client request rate

non-critical-infra/hosts/staging-hydra/hydra.nix
messed this up and only noticed it after deployment. Buts its now deployed and works: https://staging-hydra.nixos.org/machines
=> fix: staging-hydra secret permissions for server and client

non-critical-infra/modules/mailserver/mailing-lists.nix, non-critical-infra/secrets/nixcon-email-login.umbriel
It's getting harder and harder to try to keep track of NixCon emails, let's enable the use of freescout too.
Same as #748 and #746 and others. I'll onboard the account onto freescout once merged and deployed.
CC @ners @john-rodewald @Lassulus
=> Store NixCon emails for freescout

non-critical-infra/modules/mailserver/mailing-lists.nix
Also alias cfp to nixcon, because we can use freescout to manage that after #800 
Ping @ners @ra33it0 @Lassulus @a-kenji because of the cfp@nixos.org change
=> Remove personal nixcon email forwards

dns/nixos.org.js, flake.lock, flake.nix, non-critical-infra/hosts/caliban/default.nix, non-critical-infra/hosts/caliban/nixpkgs-swh.nix
The goal is to make a revival of the project described in this [blog post](https://www.tweag.io/blog/2020-06-18-software-heritage/).
This has been running for several years on the nix-community infrastructure but it stopped working about 2 years ago, when we (the nix-community) decided to stop using the buildkite CI.
After some informal discussions with some of you, it appears this could be deployed on the NixOS non critical infra.
Every day, a `sources.json` file is generated by evaluating nixpkgs. This file contains a description of all external source codes used by nixpkgs. This file can then be consumed by the Software Heritage infrastructure in order to archive our sources.
=> caliban: run the nixpkgs-swh project

non-critical-infra/modules/mailserver/mailing-lists.nix, non-critical-infra/secrets/elections-email-login.umbriel
Will set up freescout once deployed, but the @NixOS/ec-2025 can also send emails with scripts with the SMTP credentials in the vault (if you don't have a vault account, ask one of the admins: https://github.com/NixOS/org/blob/main/doc/vault.md#admins)
=> Add elections email

builders/instances/hopeful-rivest.nix
I was too optimistic.  After seeing repeated kills of Firefox builds during linking, I think this is more harm than good as it was. Perhaps some of the builds got more expensive over time.
The graph doesn't look good lately:
https://grafana.nixos.org/d/rYdddlPWk/node-exporter-full?orgId=1&var-job=node&var-node=hopeful-rivest.builder.nixos.org:9100&from=now-7d&to=now&viewPanel=panel-78
=> builders aarch64: do NOT useTmpfs, not even on hopeful-rivest

flake.lock
I wanted the builders to have a kernel with a bugfix that's affecting us: https://github.com/NixOS/nixpkgs/issues/438765
=> Lock file: update nixpkgs

build/hydra-proxy.nix
We're currently rate-limiting the endpoint for metrics and the limit isn't enough to view metrics for all jobs. For example [this](https://hydra.nixos.org/job/nixpkgs/trunk/metrics#tabs-charts) currently fails. This patch ensures that these endpoints aren't rate-limited.
=> hydra-proxy: Don't rate limit the metrics endpoint

README.md
Update the link to the bi-weekly sync since we're not using Jitsi anymore.
=> README: Update video call link for bi-weekly sync

build/haumea/network.nix, build/haumea/postgresql.nix, build/hydra.nix, build/mimas/network.nix
Lower latency, reduced compute, simpler bootstrap for new machines.
Already in production. Will yeet the wireguard setup next.
https://docs.hetzner.com/robot/dedicated-server/network/vswitch/
=> Migrate hydra db connection to hetzner private vlan

dns/nixos.org.js
At the moment tracker.security.nixos.org points to the older staging instance, this PR adds `tracker-staging` and points the tracker.security.nixos.org to the new production host. When this is applied, alerts will fire as the new host doesn't have TLS certs yet and thus the service will appear down briefly.
PS. The IPv6 is correct but not reachable at the moment, will be fixed later in the day.
=> dns: Point tracker.security.n.o to production host

dns/nixos.org.js
We want to send clickable confirmation links with static target and list of clicked links in the server logs, so probably an alias to a personal VPS of an SC member should be the simplest
=> nixos.org.js : add an alias for an election-related service

build/nginx-error-pages/403.html, build/nginx-error-pages/502.html, terraform/cache-staging/index.html, terraform/cache/index.html, terraform/nixpkgs-tarballs/index.html
Update the NixOS logo used treewide. Uses logo assets from brand.nixos.org. This URL should be stable for the foreseeable future.
=> Update NixOS logo
